In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
%load_ext line_profiler

In [3]:
import itertools
import torch

from tsvar.simulate import GrangerBuscaSimulator
from tsvar.wold_model import VariationalWoldModel

---

## Generate small toy example dataset

Define model parameters

In [4]:
dim = 3

baseline = np.array([0.1, 0.1, 0.2])

# adjacency[i,j] = magnitude of influence from i to j
adjacency = np.array([
    [0.3, 0.8, 0.1],
    [0.2, 0.3, 0.1],
    [0.2, 0.1, 0.0]
])

end_time = 1e5

for i, j in itertools.product(range(dim), repeat=2):
    print(f"w({j:d} -> {i:d}) = {adjacency[j,i]:.2f}")

w(0 -> 0) = 0.30
w(1 -> 0) = 0.20
w(2 -> 0) = 0.20
w(0 -> 1) = 0.80
w(1 -> 1) = 0.30
w(2 -> 1) = 0.10
w(0 -> 2) = 0.10
w(1 -> 2) = 0.10
w(2 -> 2) = 0.00


Simulate a dataset

In [5]:
wold_sim = GrangerBuscaSimulator(mu_rates=baseline, Alpha_ba=adjacency, Beta_b=np.ones((dim,)))
events = wold_sim.simulate(end_time, seed=42)
events = [torch.tensor(ev, dtype=torch.float) for ev in events]


print(list(map(len, events)))
print()
print(events[0])
print()
print(events[1])
print()
print(events[2])

[36304, 55138, 28497]

tensor([2.5502e+00, 3.3542e+00, 9.4456e+00,  ..., 9.9993e+04, 9.9998e+04,
        9.9998e+04])

tensor([1.0916e+01, 1.1661e+01, 1.1825e+01,  ..., 9.9996e+04, 9.9996e+04,
        9.9997e+04])

tensor([5.7092e+00, 2.1376e+01, 2.8914e+01,  ..., 9.9992e+04, 9.9993e+04,
        9.9995e+04])


---

## Test variational inference algorithm

Create model object and set the data.

In [6]:
self = VariationalWoldModel(verbose=True)
self.set_data(events)

Define the parameters of the prior.

In [15]:
as_pr = 1.0 * np.ones((dim + 1, dim))
ar_pr = 1.0 * np.ones((dim + 1, dim))

# lamb = 2.0 * (dim + 1) * np.ones(dim + 1)
lamb = 0.01 * self.n_jumps

zc_pr = [1.0 * np.ones((len(events[i]), dim+1)) for i in range(dim)]

In [16]:
self.fit(as_pr=as_pr, ar_pr=ar_pr, zc_pr=zc_pr, lamb=lamb, max_iter=100, tol=1e-5)

-------------------------------------------------- 0
Alpha posterior shape:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Z posterior probabilities
[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 ...
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]
-------------------------------------------------- 1
[36304 55138 28497]
Alpha posterior shape:
[[ 8977.   13685.5   7025.25]
 [ 8977.   13685.5   7025.25]
 [ 8977.   13685.5   7025.25]
 [ 8977.   13685.5   7025.25]]
Z posterior probabilities
[[0.25    0.25    0.25    0.25   ]
 [0.25    0.25    0.25    0.25   ]
 [0.28135 0.15595 0.28135 0.28135]
 ...
 [0.50994 0.25299 0.10494 0.13213]
 [0.49364 0.15116 0.06928 0.28591]
 [0.47078 0.08323 0.30903 0.13696]]
-------------------------------------------------- 2
[36304 55138 28497]
Alpha posterior shape:
[[16614.91589 25004.17266 13137.0939 ]
 [ 6246.02649  9872.0265   4846.62005]
 [ 7477.21776 11526.46175  5799.0177 ]
 [ 5569.83986  8339.3391   4318.2

RuntimeError: Negative alpha!