In [1]:
import numpy as np
from sklearn import preprocessing
from gb import GrangerBusca, simulate

np.random.seed(1234)

# Define parameters
mu_rates = np.array([0.1, 0.1, 0.1])
Alpha_ba = np.array([[0.0, 1.0, 0.0],
                     [0.7, 0.3, 0.0],
                     [0.8, 0.0, 0.2]])
Beta_ba = np.ones((3, 3))

# Simulate timestamps
sim = simulate.GrangeBuscaSimulator(mu_rates=mu_rates, Alpha_ba=Alpha_ba, Beta_ba=Beta_ba)
timestamps = sim.simulate(forward=1e5)
print(f'Simulated {sum(map(len, timestamps)):d} timestamps')

# Fit the model
granger_model = GrangerBusca(
    alpha_prior=1.0/len(timestamps), 
    num_iter=1000, metropolis=True, beta_strategy=1)
granger_model.fit(timestamps)

alpha_ = preprocessing.normalize(granger_model.Alpha_.toarray(),"l1")
mu_ = granger_model.mu_

# Print estimated parameters
print('mu:', mu_.round(2))
print('alpha:')
print(alpha_.round(2))

Simulated 143638 timestamps
mu: [0.25 0.28 0.06]
alpha:
[[0.22 0.73 0.05]
 [0.42 0.56 0.03]
 [0.73 0.01 0.27]]
